/*
 * coner-core-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.coner.core.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * AddRawTimeToFirstRunLackingRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-16T23:53:17.396Z")
public class AddRawTimeToFirstRunLackingRequest {
  @SerializedName("rawTime")
  private BigDecimal rawTime = null;

  public AddRawTimeToFirstRunLackingRequest rawTime(BigDecimal rawTime) {
    this.rawTime = rawTime;
    return this;
  }

   /**
   * Get rawTime
   * @return rawTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getRawTime() {
    return rawTime;
  }

  public void setRawTime(BigDecimal rawTime) {
    this.rawTime = rawTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddRawTimeToFirstRunLackingRequest addRawTimeToFirstRunLackingRequest = (AddRawTimeToFirstRunLackingRequest) o;
    return Objects.equals(this.rawTime, addRawTimeToFirstRunLackingRequest.rawTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rawTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddRawTimeToFirstRunLackingRequest {\n");
    
    sb.append("    rawTime: ").append(toIndentedString(rawTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

