/*
 * coner-core-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.14
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.coner.core.client.api;

import org.coner.core.client.ApiException;
import org.coner.core.client.model.AddRegistrationRequest;
import org.coner.core.client.model.ErrorMessage;
import org.coner.core.client.model.GetEventRegistrationsResponse;
import org.coner.core.client.model.RegistrationApiEntity;
import org.coner.core.client.model.ValidationErrorMessage;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RegistrationsApi
 */
@Ignore
public class RegistrationsApiTest {

    private final RegistrationsApi api = new RegistrationsApi();

    
    /**
     * Add a new registration
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addRegistrationTest() throws ApiException {
        String eventId = null;
        AddRegistrationRequest body = null;
        api.addRegistration(eventId, body);

        // TODO: test validations
    }
    
    /**
     * Get a list of all registrations at an event
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEventRegistrationsTest() throws ApiException {
        String eventId = null;
        GetEventRegistrationsResponse response = api.getEventRegistrations(eventId);

        // TODO: test validations
    }
    
    /**
     * Get a specific registration
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRegistrationTest() throws ApiException {
        String eventId = null;
        String registrationId = null;
        RegistrationApiEntity response = api.getRegistration(eventId, registrationId);

        // TODO: test validations
    }
    
}
